### ISSUE TITLE
Bitbucket URL's formatted incorrectly

### ISSUE THREAD

**Issue by veqryn** [markvincze/sabledocs#70]
Our bitbucket URL's (self hosted bitbucket, not sure if that makes a difference) look like this:
```
https://bitbucket.corp.mycompany.com/projects/myteam/repos/myrepo/browse/dir1/dir2/myfile.proto?at=refs%2Fheads%2Fmain#27
```
(If the branch is main, the `at=refs%2Fheads%2Fbranch` is optional)

So I created the sabledocs.toml like so:
```toml
repository-type = "bitbucket"
repository-url = "https://bitbucket.corp.mycompany.com/projects/myteam/repos/myrepo"
repository-branch = "main"
repository-dir = "dir1/dir2"
```

Unfortunately, the generated source links turn out wrong:
```
https://bitbucket.corp.mycompany.com/projects/myteam/repos/myrepo/src/main/myfile.proto#lines-26
```
